fruit="mango"
print(len(fruit))
print(fruit[-4:-2])
print(fruit[1:3])
# print(fruit[0:5])
# print(fruit[1:4])
# print(fruit[2:3])
# print(fruit[3:2])
# print(fruit[4:1])
# print(fruit[5:0])
# print(fruit[-0:-5])
# print(fruit[-1:-4])
# print(fruit[-2:-3])
# print(fruit[-3:-2])
# print(fruit[-4:-1])
# print(fruit[-5:-0])